### ISSUE TITLE
Background property does not work.

### ISSUE THREAD

**Issue by MairwunNx** [JamesCoyle/WPFModernScrollbarStyle#1]
![image](https://user-images.githubusercontent.com/39625750/42529837-2e1feb98-8488-11e8-92a7-ff404b7a4bbb.png)

I did everything according to the instructions, added in App.xaml, it appeared, everything is beautiful, but unfortunately the color does not change.

If screenshot not loaded, try it https://imgur.com/a/d47ffNL

If i remove your Scrollbar i get it

![image](https://user-images.githubusercontent.com/39625750/42530039-c61cac06-8488-11e8-8137-8f89686aa9ec.png)

**Comment by JamesCoyle** [comment]
Does the background show if you set it on the window instead of the scrollviewer?

**Comment by MairwunNx** [comment]
@JamesCoyle yes.

**Comment by JamesCoyle** [comment]
I've just edited the file so it should now allow the background to be set on the scrollviewer. Let me know if it works for you.

**Comment by MairwunNx** [comment]
@JamesCoyle Все отлично работает 👍
